name: DarkCraft
main: fromproject.org.darkcraft.DarkCraft
version: 0.0.1-SNAPSHOT
commands:
  helloworld:
    description: Tell server to "Hello World!" to chat
    usage: /helloworld
    permission: DarkCraft.helloworld
    permission-message: You don't have <permission> permission
